# Use system Python packages instead of conda environment
[deps]
# Comment out dependencies that will be available in system Python

[pip.deps]
# These will use the pre-installed packages in /opt/venv
