services:
  quantummambo:
    build:
      context: .
      dockerfile: Dockerfile
    image: quantummambo:latest
    container_name: quantummambo-dev
    volumes:
      # Mount the entire source directory for live development
      - ./src:/app/src
      - ./L1.jl:/app/L1.jl
      - ./LCU.jl:/app/LCU.jl
      - ./pyMAMBO.py:/app/pyMAMBO.py
      # Mount the SAVED directory to persist results
      - ./SAVED:/app/SAVED
      # Mount a results directory for output
      - ./results:/app/results
    working_dir: /app
    # Interactive mode for development
    stdin_open: true
    tty: true
    # Override default command for interactive use
    command: /bin/bash
    
  # Service for running specific calculations
  quantummambo-calc:
    build:
      context: .
      dockerfile: Dockerfile
    image: quantummambo:latest
    volumes:
      # Mount source code for live development
      - ./src:/app/src
      - ./L1.jl:/app/L1.jl
      - ./LCU.jl:/app/LCU.jl
      - ./pyMAMBO.py:/app/pyMAMBO.py
      - ./SAVED:/app/SAVED
      - ./results:/app/results
    working_dir: /app
    # This service can be used to run specific calculations
    # Usage: docker-compose run --rm quantummambo-calc lih
    entrypoint: ["julia", "--project=.", "L1.jl"]
    
  # Ultra-fast service using PackageCompiler system image
  quantummambo-fast:
    build:
      context: .
      dockerfile: Dockerfile.sysimage
    image: quantummambo:sysimage
    container_name: quantummambo-fast
    volumes:
      # Mount source code for live development
      - ./src:/app/src
      - ./L1.jl:/app/L1.jl
      - ./LCU.jl:/app/LCU.jl
      - ./pyMAMBO.py:/app/pyMAMBO.py
      - ./SAVED:/app/SAVED
      - ./results:/app/results
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/bash
    
  # Ultra-fast calculation service
  quantummambo-calc-fast:
    build:
      context: .
      dockerfile: Dockerfile.sysimage
    image: quantummambo:sysimage
    volumes:
      # Mount source code for live development
      - ./src:/app/src
      - ./L1.jl:/app/L1.jl
      - ./LCU.jl:/app/LCU.jl
      - ./pyMAMBO.py:/app/pyMAMBO.py
      - ./SAVED:/app/SAVED
      - ./results:/app/results
    working_dir: /app
    # Usage: docker-compose run --rm quantummambo-calc-fast lih
    entrypoint: ["run_mambo_fast.sh"]
    
  # Ultra-fast LCU service
  quantummambo-lcu-fast:
    build:
      context: .
      dockerfile: Dockerfile.sysimage
    image: quantummambo:sysimage
    volumes:
      # Mount source code for live development
      - ./src:/app/src
      - ./L1.jl:/app/L1.jl
      - ./LCU.jl:/app/LCU.jl
      - ./pyMAMBO.py:/app/pyMAMBO.py
      - ./SAVED:/app/SAVED
      - ./results:/app/results
    working_dir: /app
    # Usage: docker-compose run --rm quantummambo-lcu-fast lih
    entrypoint: ["run_lcu_fast.sh"] 